name: atomic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.2
  go_router: 5.0.5
  flutter_riverpod: 2.0.2
  riverpod: 2.0.2
  dio: 4.0.6
  retrofit: 3.3.1
  google_fonts: 3.0.1
  logger: 1.1.0
  shared_preferences: 2.0.15
  flutter_secure_storage: 6.0.0
  connectivity_plus: 2.3.9
  json_annotation: 4.7.0
  freezed_annotation: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  mason_cli: 0.1.0-dev.37
  freezed: 2.2.0
  json_serializable: 6.5.3
  retrofit_generator: 4.2.0
  build_runner: 2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - google_fonts/

